language: java

script: cd editor && mvn clean test 

jdk:
  - openjdk7
  - oraclejdk7
  - openjdk6

branches:
  except:
    - gh-pages

notifications:
  email:
    recipients:
      - vvakame@gmail.com
      - u1aryz.d@gmail.com

